library:
  source-dirs: src
tests:
  Chapter18-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter18
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- QuickCheck
- checkers
- base >= 4.7 && < 5
name: Chapter18
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/Chapter18
license: BSD3
executables:
  Chapter18-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter18
description: Please see the README on GitHub at <https://github.com/githubuser/Chapter18#readme>
