library:
  source-dirs: src
tests:
  FunctionalProgramming-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunctionalProgramming
copyright: 2019 Author name here
maintainer: example@example.com
ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
dependencies:
- array
- split
- containers
- base >= 4.7 && < 5
name: FunctionalProgramming
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/FunctionalProgramming
license: BSD3
executables:
  FunctionalProgramming-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunctionalProgramming
description: Please see the README on GitHub at <https://github.com/githubuser/FunctionalProgramming#readme>
