library:
  source-dirs: src
tests:
  Chapter17-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter17
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- checkers
- QuickCheck
- base >= 4.7 && < 5
name: Chapter17
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/Chapter17
license: BSD3
executables:
  Chapter17-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chapter17
description: Please see the README on GitHub at <https://github.com/githubuser/Chapter17#readme>
