library:
  source-dirs: src
tests:
  AFewMonadsMore-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AFewMonadsMore
copyright: 2019 Author name here
maintainer: example@example.com
ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
dependencies:
- random
- base >= 4.7 && < 5
- mtl
name: AFewMonadsMore
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/AFewMonadsMore
license: BSD3
executables:
  AFewMonadsMore-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AFewMonadsMore
description: Please see the README on GitHub at <https://github.com/githubuser/AFewMonadsMore#readme>
